// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Musica2.Context;

#nullable disable

namespace Musica2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240201131547_migracionMusica")]
    partial class migracionMusica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Musica2.Models.Artistas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numeroCanciones")
                        .HasColumnType("int");

                    b.Property<int>("oyentesMensuales")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("Musica2.Models.Canciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistasId")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistasId");

                    b.ToTable("Canciones");
                });

            modelBuilder.Entity("Musica2.Models.CancionesUsuarios", b =>
                {
                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.Property<int>("CancionesId")
                        .HasColumnType("int");

                    b.HasKey("UsuariosId", "CancionesId");

                    b.HasIndex("CancionesId");

                    b.ToTable("CancionesUsuarios");
                });

            modelBuilder.Entity("Musica2.Models.DatosBancarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("int");

                    b.Property<string>("fechaExpiracion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId")
                        .IsUnique();

                    b.ToTable("DatosBancarios");
                });

            modelBuilder.Entity("Musica2.Models.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Musica2.Models.Canciones", b =>
                {
                    b.HasOne("Musica2.Models.Artistas", null)
                        .WithMany("Canciones")
                        .HasForeignKey("ArtistasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musica2.Models.CancionesUsuarios", b =>
                {
                    b.HasOne("Musica2.Models.Canciones", "Canciones")
                        .WithMany()
                        .HasForeignKey("CancionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Musica2.Models.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canciones");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Musica2.Models.DatosBancarios", b =>
                {
                    b.HasOne("Musica2.Models.Usuarios", null)
                        .WithOne("DatosBancarios")
                        .HasForeignKey("Musica2.Models.DatosBancarios", "UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Musica2.Models.Artistas", b =>
                {
                    b.Navigation("Canciones");
                });

            modelBuilder.Entity("Musica2.Models.Usuarios", b =>
                {
                    b.Navigation("DatosBancarios")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
